# Generated by Django 3.1.4 on 2021-09-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinments',
            name='expire_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
